### ISSUE TITLE
Global Marktplace dont work

### ISSUE THREAD

**Issue by Dernerd** [wpmudev/marketpress#3]
Version 3.3 dont work in Global Marketplacemode in Multisite, my old Version 2.9.5.9 works, but than the Upfrontthemes on the Blogs dont work.

**Comment by skorepios** [comment]
Yes, it doesn't work for me either. Not even my old version 2.9.5.9 - I get this error:


Fatal error: Uncaught Error: Call to undefined function create_function() in /home3/joko/public_html/wp-content/plugins/marketpress-master/includes/admin/widgets/cart.php:81 Stack trace: #0 /home3/joko/public_html/wp-content/plugins/marketpress-master/marketpress.php(494): require_once() #1 /home3/joko/public_html/wp-content/plugins/marketpress-master/marketpress.php(417): Marketpress->load_widgets() #2 /home3/joko/public_html/wp-content/plugins/marketpress-master/marketpress.php(101): Marketpress->__construct() #3 /home3/joko/public_html/wp-content/plugins/marketpress-master/marketpress.php(1148): Marketpress::get_instance() #4 /home3/jokopublic_html/wp-admin/includes/plugin.php(2313): include_once('/home3/joko...') #5 /hplome3/joko/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape('marketpress-mas...') #6 {main} thrown in /home3/joko/public_html/wp-content/plugins/marketpress-master/includes/admin/widgets/cart.php on line 81
